CREATE TABLE place (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE UNIQUE,
  -- Autogenerated from name (see slugify); de-duplicated with a -N suffix
  slug TEXT NOT NULL UNIQUE,
  url TEXT,
  notes TEXT,
  cuisine TEXT,
  lat REAL,
  lng REAL,
  tags TEXT NOT NULL DEFAULT '[]',
  archived INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- A place's menu: "Buffet", "Ramen bowl", ... Prices live in menu_item_price.
CREATE TABLE menu_item (
  id INTEGER PRIMARY KEY,
  place_id INTEGER NOT NULL REFERENCES place (id) ON DELETE CASCADE,
  name TEXT NOT NULL COLLATE NOCASE,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (place_id, name)
);

-- Append-only price history; the newest row is the current price.
CREATE TABLE menu_item_price (
  id INTEGER PRIMARY KEY,
  menu_item_id INTEGER NOT NULL REFERENCES menu_item (id) ON DELETE CASCADE,
  price_cents INTEGER NOT NULL CHECK (price_cents > 0),
  recorded_by TEXT NOT NULL,
  recorded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX menu_item_price_item ON menu_item_price (menu_item_id, recorded_at);

CREATE TABLE session (
  id INTEGER PRIMARY KEY,
  -- Short non-guessable slug for URLs (internal FKs use id)
  public_id TEXT NOT NULL UNIQUE,
  date TEXT NOT NULL UNIQUE,
  mode TEXT NOT NULL DEFAULT 'democracy'
    CHECK (mode IN ('democracy', 'dictatorship', 'random')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'finalized')),
  dictator_name TEXT,
  chosen_place_id INTEGER REFERENCES place (id),
  finalized_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE participant (
  session_id INTEGER NOT NULL REFERENCES session (id) ON DELETE CASCADE,
  name TEXT NOT NULL COLLATE NOCASE,
  joined_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (session_id, name)
);

CREATE TABLE vote (
  session_id INTEGER NOT NULL REFERENCES session (id) ON DELETE CASCADE,
  voter_name TEXT NOT NULL COLLATE NOCASE,
  place_id INTEGER NOT NULL REFERENCES place (id),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (session_id, voter_name)
);

CREATE INDEX vote_session_place ON vote (session_id, place_id);
