import type { Generated } from "kysely";

export type SessionMode = "democracy" | "dictatorship" | "random";
export type SessionStatus = "open" | "finalized";

export interface PlaceTable {
  id: Generated<number>;
  name: string;
  /** Autogenerated from name, e.g. "sushi-palace" */
  slug: string;
  url: string | null;
  notes: string | null;
  /** e.g. "sushi", "pizza", "buffet" — free text */
  cuisine: string | null;
  /** Human-readable street address, free text */
  address: string | null;
  lat: number | null;
  lng: number | null;
  /** JSON array of strings */
  tags: Generated<string>;
  /** SQLite boolean: 0 | 1 */
  archived: Generated<number>;
  created_by: string;
  created_at: Generated<string>;
}

export interface PlaceHoursTable {
  place_id: number;
  /** ISO weekday: 1=Mon … 7=Sun. No row = closed that day. */
  weekday: number;
  /** 'HH:MM' 24h Helsinki wall-clock */
  open_time: string;
  close_time: string;
  /** Lunch window, independent of the (non-lunch) open–close range;
   * both set or both null (not recorded) */
  lunch_open: string | null;
  lunch_close: string | null;
}

export interface PlaceClosureTable {
  id: Generated<number>;
  place_id: number;
  /** 'YYYY-MM-DD', inclusive */
  start_date: string;
  end_date: string;
  reason: string;
  created_by: string;
  created_at: Generated<string>;
}

export interface PlaceRatingTable {
  id: Generated<number>;
  place_id: number;
  rater_name: string;
  /** 0.5–5 stars in half-star steps; a rater's newest row is their current rating */
  rating: number;
  rated_at: Generated<string>;
}

export interface MenuItemTable {
  id: Generated<number>;
  place_id: number;
  name: string;
  created_by: string;
  created_at: Generated<string>;
}

export interface MenuItemPriceTable {
  id: Generated<number>;
  menu_item_id: number;
  price_cents: number;
  recorded_by: string;
  recorded_at: Generated<string>;
}

export interface SessionTable {
  id: Generated<number>;
  /** Short non-guessable slug for URLs, e.g. "zesty-taco-7k2m" */
  public_id: string;
  /** 'YYYY-MM-DD' in Europe/Helsinki time */
  date: string;
  mode: Generated<SessionMode>;
  status: Generated<SessionStatus>;
  dictator_name: string | null;
  chosen_place_id: number | null;
  finalized_at: string | null;
  created_at: Generated<string>;
}

export interface ParticipantTable {
  session_id: number;
  name: string;
  joined_at: Generated<string>;
}

export interface VoteTable {
  session_id: number;
  voter_name: string;
  place_id: number;
  updated_at: Generated<string>;
}

export interface DB {
  place: PlaceTable;
  place_hours: PlaceHoursTable;
  place_closure: PlaceClosureTable;
  place_rating: PlaceRatingTable;
  menu_item: MenuItemTable;
  menu_item_price: MenuItemPriceTable;
  session: SessionTable;
  participant: ParticipantTable;
  vote: VoteTable;
}
